"""Generate package-local fixed category catalogs; --check never writes files."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    rows = json.loads((ROOT / "shared/category-catalog.json").read_text(encoding="utf-8"))
    names = [row["name"] for row in rows]
    if len(names) != 30 or len(set(names)) != 30:
        raise ValueError("The fixed catalog must contain exactly 30 unique names")
    ts = "// Generated by scripts/generate_categories.py. Do not edit.\n"
    ts += "export const CATEGORY_CATALOG = " + json.dumps(rows, indent=2) + " as const;\n"
    ts += "export type CategoryName = typeof CATEGORY_CATALOG[number]['name'];\n"
    ts += "export const CATEGORIES: readonly CategoryName[] = CATEGORY_CATALOG.map((row) => row.name);\n"
    return {
        "backend/category_names.py": "# Generated by scripts/generate_categories.py. Do not edit.\nCATEGORIES = " + repr(names) + "\n",
        "frontend/src/categoryCatalog.generated.ts": ts,
        "q/src/categoryCatalog.generated.ts": ts,
    }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        target = ROOT / name
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            target.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale generated catalogs: " + ", ".join(stale))
    print("Fixed category catalogs verified" if args.check else "Fixed category catalogs generated")

if __name__ == "__main__":
    main()
